language: cpp
cache: apt
compiler:
    - gcc
    - clang
before_install:
    - travis_retry sudo apt-get update -qq
    - travis_retry apt-get install libboost-python-dev cxxtest cmake extra-cmake-modules
before_script:
    - mkdir build
    - cd build
script: cmake .. && make all test
